#*******************************************************************************
#github_actions_CD.yml
#*******************************************************************************

#Purpose:
#GitHub Actions is a continuous integration and continuous delivery (CI/CD)
#platform that allows to automate the build, test, and deployment pipeline.
#The purpose of this file is to give instructions to GitHub on how to do the
#image deployment to Docker Hub.
#Author:
#Jeffrey Wade, CEdric H. David, 2024.
